name: Generate Stats Images

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '5 0 * * *'   # every day at 00:05 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'

    - name: Install deps
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements.txt

    - name: Generate images
      run: |
        python generate_images.py --user "$GH_USERNAME"
      env:
        GH_USERNAME: isaiahiruoha          # ← your exact new handle
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    - name: Commit results
      run: |
        git config --global user.name 'github-stats[bot]'
        git config --global user.email 'github-stats[bot]@example.com'
        git add .
        git commit -m 'Update generated files' || true
        git push
